# Generated by Django 6.0.5 on 2026-05-22 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra')),
                ('state', models.CharField(choices=[('active', 'Activo'), ('refunded', 'Reembolsado'), ('removed', 'Removido')], default='active', max_length=20, verbose_name='Estado del artículo')),
            ],
            options={
                'verbose_name': 'Elemento de carrito',
                'verbose_name_plural': 'Elementos de carritos',
                'db_table': 'add_to',
            },
        ),
        migrations.CreateModel(
            name='Choreography',
            fields=[
                ('choreography_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=255, verbose_name='Nombre de la canción')),
                ('genre', models.CharField(max_length=100, verbose_name='Género musical')),
                ('difficulty_level', models.CharField(max_length=50, verbose_name='Nivel de dificultad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Coreografía',
                'verbose_name_plural': 'Coreografías',
                'db_table': 'choreography',
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('state', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='Estado')),
                ('id_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Origen o Referencia de Inscripción')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'enroll',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de calificación')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'rate',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('shopping_cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado del carrito')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Carrito de compras',
                'verbose_name_plural': 'Carritos de compras',
                'db_table': 'shopping_cart',
            },
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('clip_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.IntegerField(verbose_name='Número de parte o sección')),
                ('video_url', models.URLField(max_length=500, verbose_name='URL del video')),
            ],
            options={
                'verbose_name': 'Video Clip',
                'verbose_name_plural': 'Video Clips',
                'db_table': 'video_clip',
                'ordering': ['part_number'],
            },
        ),
    ]
