# Generated by Django 6.0.5 on 2026-05-22 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='choreography',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_choreographies', to=settings.AUTH_USER_MODEL, verbose_name='Creador/Profesor'),
        ),
        migrations.AddField(
            model_name='addto',
            name='choreography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.choreography', verbose_name='Coreografía'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='choreography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academy.choreography', verbose_name='Coreografía'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='rate',
            name='choreography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='academy.choreography', verbose_name='Coreografía'),
        ),
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='addto',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academy.shoppingcart', verbose_name='Carrito de compras'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='choreography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_clips', to='academy.choreography', verbose_name='Coreografía'),
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('user', 'choreography')},
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'choreography')},
        ),
        migrations.AlterUniqueTogether(
            name='addto',
            unique_together={('shopping_cart', 'choreography')},
        ),
    ]
