# Generated by Django 6.0.5 on 2026-06-14 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to=settings.AUTH_USER_MODEL)),
                ('video_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='academy.videoclip')),
            ],
            options={
                'verbose_name': 'Video visto',
                'verbose_name_plural': 'Videos vistos',
                'db_table': 'video_view',
                'unique_together': {('user', 'video_clip')},
            },
        ),
    ]
