# Generated by Django 6.0.5 on 2026-07-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_videoview'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreography',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa en catálogo'),
        ),
    ]
