# Generated by Django 6.0.5 on 2026-07-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0003_videoview"),
    ]

    operations = [
        migrations.AddField(
            model_name="choreography",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción de la clase"
            ),
        ),
        migrations.AddField(
            model_name="choreography",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="URL de la miniatura de portada",
            ),
        ),
        migrations.AddField(
            model_name="videoclip",
            name="media_type",
            field=models.CharField(
                choices=[("video", "Video"), ("image", "Imagen")],
                default="video",
                max_length=10,
                verbose_name="Tipo de recurso",
            ),
        ),
        migrations.AlterField(
            model_name="videoclip",
            name="video_url",
            field=models.URLField(
                max_length=500, verbose_name="URL del recurso (Video o Imagen)"
            ),
        ),
    ]
