# Generated by Django 6.0.5 on 2026-07-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_choreography_description_choreography_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreography',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa en catálogo'),
        ),
    ]
