# Generated by Django 6.0.5 on 2026-07-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_choreography_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Clave de idempotencia",
            ),
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Método de pago"
            ),
        ),
    ]
